### PR TITLE
Add meson build file

### PR DESCRIPTION
**Pull request by bioinfornatics**
Dear,

In order to be able to build with meson. I added a `meson.build` file

```
$ meson build
$ ninja -C build
$ ninja install
````

### CODE REVIEW

**Comment by schveiguy** [comment]
Once we get the io one working, we can work on this one.

**Comment by schveiguy** [comment]
I'm unsure whether we should follow the same path as io (and limit to 2.088.1) or wait for a fix. I'm fine either way. I'm also not sure if we should try the `cast(shared)null` workaround temporarily.

**Comment by schveiguy** [comment]
OK, I think we can continue with this, once #26 tests pass and is merged. I removed the requirement for std.io by versioning out the `IODev` deprecations (which is the only reason std.io was required) and making std.io optional. The meson build I would think shouldn't care at all about std.io.

**Comment by schveiguy** [comment]
@bioinfornatics it passed, so I'm rerunning these checks. We can start from there.

**Comment by schveiguy** [comment]
passes! make sure meson build runs on CI and runs unittests (similar to io). then I think we are good to merge.

**Comment by bioinfornatics** [comment]
hi @schveiguy , unfortunately I not enough time these day.
I close the request
BTW meson is a good and simple build system ;-)

**Pull request closed without merging**
